./" Manpage for your script
.TH man 1 „06 June 2022" "1.0" "Compare man page"
.SH NAME
compare - compute and check control sums of files and text with graphical interface
.SH SYNOPSIS
compare [FILE] [FILE2]
.SH DESCRIPTION
Print, check or compare checksums of files or text using different algorithms in zenity user interface
.SH OPTIONS
There are 5 options:
    1. Calculate control sum of selected file
    2. Compare two files
    3. Calculate control sum of entered text
    4. Compare file and text
    5. Choose comparing algorithm
.SH ALGORITHMS
There are 6 algorithms to choose:
    -sha256
    -sha1
    -sha224
    -sha384
    -sha512
    -md5
.SH AUTHOR
Written by Jakub Kwidzinski
.SH REPORTING BUGS
email: jkwidzinski@gmail.com
.SH COPYRIGHT
Copyrith 2022 Jakub Kwidzinski. License GPLv3+: GNU GPL version 3 or later <https://gun.org/licenses/gpl.html>. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.